import os
import sys
import secrets
from pathlib import Path
from dotenv import load_dotenv
import tempfile
import json

# Ensure we can import from shared
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from shared.circle_client import get_circle_client

# Import Circle SDK for Entity Secret registration
try:
    from circle.web3 import utils as circle_utils
except ImportError:
    print("❌ Circle SDK not installed. Installing...")
    os.system("pip install circle-developer-controlled-wallets")
    from circle.web3 import utils as circle_utils


def bootstrap():
    """
    Zero-Slop Bootstrap: Fresh Environment Setup for Circle Integration.
    
    Flow:
    1. Create .env if missing
    2. Read CIRCLE_API_KEY (or prompt)
    3. Generate CIRCLE_ENTITY_SECRET locally
    4. Write both to .env
    5. Use in-memory values for all subsequent operations (no re-reading from .env)
    """
    env_path = Path(".env")
    
    # 1. Ensure .env exists with template
    if not env_path.exists():
        print("✓ Creating new .env file...")
        with open(env_path, "w") as f:
            f.write("""# Agora Marketplace - Circle Integration
# Generated by bootstrap_circle.py

# Circle Developer: Your API Key (https://developers.circle.com)
CIRCLE_API_KEY=

# Circle Security: Entity Secret (generated locally, never shared)
CIRCLE_ENTITY_SECRET=

# Circle Wallets: Wallet Set ID (auto-created during bootstrap)
CIRCLE_WALLET_SET_ID=

# Arc Network Configuration
ARC_RPC_URL=https://rpc.testnet.arc.network
ARC_TESTNET_USDC=0x3600000000000000000000000000000000000000

# Redis (required for nonce replay protection)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0
NONCE_TTL_SECONDS=60

# AI Model
GROQ_API_KEY=
GROQ_MODEL=llama-3.1-8b-instant
""")
    
    # 2. Load existing .env
    load_dotenv()
    
    # 3. Get or prompt for API Key (read-only from .env)
    api_key = os.getenv("CIRCLE_API_KEY", "").strip()
    if not api_key:
        api_key = input("\n🔑 Enter your Circle API Key (from https://developers.circle.com): ").strip()
        _write_env_var("CIRCLE_API_KEY", api_key)
    else:
        print(f"✅ Found existing CIRCLE_API_KEY: {api_key[:20]}...")
    
    # 4. Generate Entity Secret LOCALLY (keep in memory, do NOT re-read from .env)
    entity_secret = os.getenv("CIRCLE_ENTITY_SECRET", "").strip()
    if entity_secret:
        print(f"✅ Found existing CIRCLE_ENTITY_SECRET: {entity_secret[:16]}...")
        print(f"   (Using existing secret. To reset, delete this line from .env)")
        secret_is_registered = True
    else:
        print("\n🔐 Generating new Entity Secret (32-byte secure random)...")
        entity_secret = secrets.token_hex(32)
        print(f"✅ Generated: {entity_secret}")
        
        # Register automatically with Circle API using SDK
        print("\n📤 Registering Entity Secret with Circle Console...")
        try:
            # Create temp directory for recovery file
            with tempfile.TemporaryDirectory() as tmpdir:
                # Pass directory path, not file path
                result = circle_utils.register_entity_secret_ciphertext(
                    api_key=api_key,
                    entity_secret=entity_secret,
                    recoveryFileDownloadPath=tmpdir  # Pass directory, not full file path
                )
                
                # Look for recovery file in the directory
                recovery_files = list(Path(tmpdir).glob("*.json"))
                if recovery_files:
                    recovery_file_path = recovery_files[0]
                    with open(recovery_file_path, 'r') as rf:
                        recovery_data = json.load(rf)
                    print(f"✅ Successfully registered Entity Secret with Circle")
                    print(f"   Recovery file created (save this securely!)")
                    # Save recovery file to project
                    safe_recovery_path = Path(".") / ".recovery" / "entity_secret_recovery.json"
                    safe_recovery_path.parent.mkdir(exist_ok=True)
                    with open(safe_recovery_path, 'w') as f:
                        json.dump(recovery_data, f, indent=2)
                    print(f"   💾 Saved to: {safe_recovery_path}")
                else:
                    print(f"✅ Successfully registered Entity Secret with Circle")
        except Exception as e:
            print(f"❌ Failed to register Entity Secret: {e}")
            print("   Make sure your CIRCLE_API_KEY is valid")
            sys.exit(1)
        
        # Save to .env
        _write_env_var("CIRCLE_ENTITY_SECRET", entity_secret)
        secret_is_registered = True
    
    # 5. Create Wallet Set (use in-memory variables, NOT .env reads)
    print("\n⛓️  Configuring Circle Wallet Set on Arc Testnet...")
    
    existing_set_id = os.getenv("CIRCLE_WALLET_SET_ID", "").strip()
    if existing_set_id:
        print(f"✅ Using existing Wallet Set: {existing_set_id}")
        wallet_set_id = existing_set_id
    else:
        print("🚀 Creating new Wallet Set...")
        try:
            # Pass in-memory api_key and entity_secret DIRECTLY to client
            # Do NOT let it re-read from .env
            client = get_circle_client(
                api_key=api_key,
                entity_secret=entity_secret
            )
            wallet_set_id = client.create_wallet_set(name="Agora_Agents")
            _write_env_var("CIRCLE_WALLET_SET_ID", wallet_set_id)
            print(f"✅ Successfully created Wallet Set: {wallet_set_id}")
        except Exception as e:
            print(f"❌ Failed to create Wallet Set: {e}")
            print("   Make sure your CIRCLE_API_KEY is valid and registered with Entity Secret in Circle Console")
            sys.exit(1)
    
    print("\n" + "="*60)
    print("✅ BOOTSTRAP COMPLETE")
    print("="*60)
    print(f"\n📝 Configuration saved to .env:")
    print(f"   - CIRCLE_API_KEY: {api_key[:30]}...")
    print(f"   - CIRCLE_ENTITY_SECRET: {entity_secret[:16]}...")
    print(f"   - CIRCLE_WALLET_SET_ID: {wallet_set_id}")
    print(f"\n🚀 Next steps:")
    print(f"   1. Start Redis: redis-server")
    print(f"   2. Run agents: python -m sdk.agent")
    print(f"   3. API server: uvicorn api.v1:app --reload")
    print()


def _write_env_var(key: str, value: str):
    """Safely append a variable to .env without duplicates."""
    env_path = Path(".env")
    existing_content = env_path.read_text() if env_path.exists() else ""
    
    # Remove old value if exists
    lines = [line for line in existing_content.split('\n') if not line.startswith(f"{key}=")]
    
    # Append new value
    if lines and lines[-1]:
        lines.append(f"{key}={value}")
    else:
        lines.append(f"{key}={value}")
    
    env_path.write_text('\n'.join(lines) + '\n')


if __name__ == "__main__":
    bootstrap()
