"""
One-shot env file generator: creates .env with fresh wallets for the
marketplace treasury + agents + buyer.

Run once::

    python scripts/setup_env.py
    source .env   # (or: export $(grep -v '^#' .env | xargs))

Re-running OVERWRITES .env. To keep an existing wallet, edit .env by hand.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agora_x402.wallet import generate_keypair

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"

# Wallets to generate. The treasury only needs an address (no signing).
SIGNING_WALLETS = ["SUMMARYBOT", "MOODREADER", "DATAWIZARD", "BUYER"]


def main() -> None:
    if ENV_PATH.exists():
        print(f"⚠️  {ENV_PATH} already exists. Delete it first to regenerate.")
        sys.exit(1)

    treasury = generate_keypair()
    lines: list[str] = [
        "# Generated by scripts/setup_env.py — DO NOT COMMIT.",
        "",
        "# ── Facilitator (marketplace) ───────────────────────────────────────────",
        "FACILITATOR_URL=http://localhost:8000",
        "FACILITATOR_DB_PATH=/tmp/agora_facilitator.db",
        "",
        "# Marketplace economics (in USDC)",
        "MARKETPLACE_LISTING_FEE=0.10",
        "MARKETPLACE_TX_FEE_BPS=250",
        f"MARKETPLACE_TREASURY_ADDRESS={treasury['address']}",
        "",
        "# ── Settlement mode ─────────────────────────────────────────────────────",
        "SETTLEMENT_MODE=mock",
        "",
        "# ── Agent defaults ──────────────────────────────────────────────────────",
        "AGENT_HOST=0.0.0.0",
        "NONCE_TTL_SECONDS=120",
        "SUMMARYBOT_URL=http://localhost:9001",
        "MOODREADER_URL=http://localhost:9002",
        "DATAWIZARD_URL=http://localhost:9003",
        "",
        "# ── Generated wallets ───────────────────────────────────────────────────",
    ]

    print()
    print(f"  Treasury        {treasury['address']}")
    for name in SIGNING_WALLETS:
        kp = generate_keypair()
        lines.append(f"{name}_PRIVATE_KEY={kp['private_key']}")
        lines.append(f"{name}_ADDRESS={kp['address']}")
        lines.append("")
        print(f"  {name:<14}  {kp['address']}")

    ENV_PATH.write_text("\n".join(lines) + "\n")
    print()
    print(f"✅ Wrote {ENV_PATH}")
    print("   Now run:  set -a && source .env && set +a")


if __name__ == "__main__":
    main()
