"""
agents/formatter_agent.py — Port 8005

Formatter Agent: produces the final polished competitive intelligence report.
Price: $0.0005 USDC per call (Nanopayment).

Takes all pipeline outputs and formats them into a clean, structured
markdown document ready for the client.
"""

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from fastapi import FastAPI, Header
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from dotenv import load_dotenv

from shared.x402_middleware import verify_payment_on_chain, make_402_response
from shared.llm import generate_gemini_content

load_dotenv()

app = FastAPI(title="Agora — Formatter Agent")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

AGENT_NAME    = "Formatter Agent"
AGENT_WALLET  = os.getenv("FORMATTER_AGENT_ADDRESS")
PRICE         = "0.0005"


class FormatRequest(BaseModel):
    topic: str
    company_context: dict = {}
    search_results: list = []
    summaries: list = []
    analyst_recommendations: Optional[dict] = None
    budget_summary: dict = {}


@app.post("/format")
async def format_report(
    request: FormatRequest,
    x_402_payment_proof: str = Header(None)
):
    # ── Step 1: Require payment ───────────────────────────────────────────────
    if not x_402_payment_proof:
        return make_402_response(AGENT_WALLET, PRICE, AGENT_NAME)

    # ── Step 2: Verify Nanopayment on Arc ─────────────────────────────────────
    verified, result = await verify_payment_on_chain(
        tx_hash=x_402_payment_proof,
        expected_recipient=AGENT_WALLET,
        expected_amount=float(PRICE)
    )
    if not verified:
        return JSONResponse(
            status_code=402,
            content={"error": f"Payment verification failed: {result}"}
        )

    # ── Step 3: Format the final report ───────────────────────────────────────
    summaries_text = "\n\n".join([
        s.get("summary", str(s)) for s in request.summaries
    ]) if request.summaries else "No summaries available"

    recommendations_text = ""
    if request.analyst_recommendations:
        recommendations_text = request.analyst_recommendations.get(
            "recommendations", ""
        )

    budget = request.budget_summary
    tx_count = budget.get("transaction_count", 0)
    total_spent = budget.get("total_spent", 0)

    prompt = f"""You are a professional report formatter. Create a polished competitive intelligence report.

Topic: {request.topic}

Research Summaries:
{summaries_text[:4000]}

Strategic Recommendations:
{recommendations_text[:3000]}

Format this into a clean, professional markdown report with:

# Competitive Intelligence Report: {request.topic}

*Generated by Agora — {tx_count} AI agent micro-transactions settled on Arc testnet*
*Total research cost: ${total_spent:.4f} USDC*

---

## Executive Summary
(2-3 sentences: what was found and why it matters)

## Key Findings
(The most important competitive intelligence points, with sub-sections)

## Strategic Recommendations
(Paste the recommendations formatted cleanly — do not paraphrase)

## Sources
(List key sources found — use the search results if available)

## Methodology
*This report was generated by Agora's autonomous multi-agent pipeline:*
- *Web Search Agent searched {len(request.search_results)} sources*
- *Extractor Agent pulled structured data from each source*
- *Summarizer Agent condensed findings across {len(request.summaries)} research batches*
- *Analyst Agent generated targeted strategic recommendations*
- *All agents were paid via Circle Nanopayments on Arc testnet*
- *Total on-chain transactions: {tx_count}*

Make it look like a real McKinsey-style document. Clean headers, bullet points, facts-first.
"""
    try:
        report_markdown = await generate_gemini_content(prompt)
        report_markdown = report_markdown.strip()
    except Exception as e:
        report_markdown = f"# Report Formatting Failed\n\nError: {str(e)}"

    return {
        "agent": AGENT_NAME,
        "topic": request.topic,
        "report_markdown": report_markdown,
        "transaction_count": tx_count,
        "total_cost": total_spent,
        "payment_verified": x_402_payment_proof,
        "cost": PRICE
    }


@app.get("/health")
async def health():
    return {"agent": AGENT_NAME, "wallet": AGENT_WALLET, "price": PRICE, "status": "ok"}
